// <auto-generated />
using System;
using CashierPOS.WebApi.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CashierPOS.WebApi.Migrations
{
    [DbContext(typeof(CashierPOSContext))]
    partial class CashierPOSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Brand", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("Create_At")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(550)
                        .HasColumnType("varchar");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("MenuId")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.ChangeShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Change_Shift_By")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("Company_Id")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("Company_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<decimal?>("End_Balance")
                        .HasColumnType("decimal(12,4)");

                    b.Property<DateTime?>("End_Shift")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Net_Sale")
                        .HasColumnType("decimal(12,4)");

                    b.Property<int>("Pos_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Print_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Shift_Status")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<decimal>("Start_Balance")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("Start_Balance_Kh")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("Start_Shift")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Total_Changed")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal?>("Total_Discount")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal?>("Total_Sale")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal?>("Total_Tax")
                        .HasColumnType("decimal(8,4)");

                    b.Property<int>("UserLogId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Change_Shift_By");

                    b.HasIndex("Company_Id");

                    b.HasIndex("UserLogId");

                    b.ToTable("ChangeShifts");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.ChangeShiftDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ChangeShift_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Create_At")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentMethod_Id")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("ChangeShift_Id");

                    b.HasIndex("PaymentMethod_Id");

                    b.ToTable("ChangeShiftDetails");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Company", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<int?>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("Create_At")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<decimal>("Exchange_Rate")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("varchar");

                    b.Property<bool?>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("NameKh")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar");

                    b.Property<decimal?>("SaleExchangeRate")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("System_Id")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("System_Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("CompanyId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("Contact")
                        .HasMaxLength(15)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("CustomerTypeCode")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<decimal?>("EarningAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("EarningPoint")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Nationality")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Contact")
                        .IsUnique()
                        .HasFilter("[Contact] IS NOT NULL");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.CustomerType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("NameKh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CustomerTypes");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.DiscountType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("CreateAt")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DiscountTypes");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Division", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("CompanyId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.ExchangeRate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("Create_At")
                        .HasColumnType("datetime");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Last_Updated")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Menu", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DivisionId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("Image")
                        .HasMaxLength(556)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("Cancelled_At")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Change")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("ChangeKh")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Company_Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("CustomerId")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("CustomerType")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<decimal?>("Delivery")
                        .IsRequired()
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Grand_Total")
                        .HasColumnType("decimal(10,4)");

                    b.Property<bool?>("Is_Deleted")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime>("Order_Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Order_Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaymentMethodId")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("PaymentTypeCode")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("ReasonTypeId")
                        .HasColumnType("varchar(36)");

                    b.Property<decimal?>("Received")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("ReceivedKh")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Reference_Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<decimal?>("Remaining")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("RemainingKh")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("SellType")
                        .HasColumnType("varchar(36)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<decimal>("Sub_Total")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("Total_Discount")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("Reference_Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.OrderDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("Create_At")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Discount_Amount")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("Discount_Percent")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("Grand_Amount")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Order_Id")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Product_Code")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("Product_Id")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("ReasonId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("Sub_Amount")
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTime?>("SynData_At")
                        .HasColumnType("datetime");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("TaxType")
                        .HasColumnType("int");

                    b.Property<decimal?>("Total_Discount")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("Order_Id");

                    b.HasIndex("Product_Id");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.OrderPayment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<decimal?>("Change")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("ChangeKh")
                        .HasColumnType("decimal(12,0)");

                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("CustomerCode")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("CustomerTypeId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("DiscountName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<decimal>("Exchange_Rate")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Order_Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("PaymentCode")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("PaymentMethodId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("PaymentTypeId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("PaymentTypeName")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<decimal?>("Received")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("ReceivedKh")
                        .HasColumnType("decimal(12,0)");

                    b.Property<string>("Reference")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<decimal?>("Remaining")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("RemainingKh")
                        .HasColumnType("decimal(12,0)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Total_Kh")
                        .HasColumnType("decimal(12,0)");

                    b.Property<DateTime>("Transaction_Date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CustomerTypeId");

                    b.HasIndex("Order_Id");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("Reference");

                    b.HasIndex("SourceId");

                    b.ToTable("OrderPayments");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.PaymentMethod", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("Create_At")
                        .HasColumnType("datetime");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.PaymentType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("PaymentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentCode")
                        .IsUnique();

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Category_Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("Company_Id")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("Create_At")
                        .HasColumnType("datetime");

                    b.Property<string>("Create_By")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("ExpiredDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Image")
                        .HasMaxLength(550)
                        .HasColumnType("varchar");

                    b.Property<bool?>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("NameKh")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<int>("Tax")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Category_Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Company_Id");

                    b.HasIndex("Create_By");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.ProductDiscount", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("DiscountId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDiscounts");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.ReasonRefundType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("Create_At")
                        .HasColumnType("datetime");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ReasonRefundTypes");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.ReasonType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("Create_At")
                        .HasColumnType("datetime");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Reason_Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ReasonTypes");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.ReturnOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("ApprovedByUserName")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<decimal>("Grand_Total")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ReturnReasonCode")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<decimal>("Sub_Total")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("Total_Discount")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.ToTable("ReturnOrders");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.ReturnOrderDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<decimal?>("Discount_Amount")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("Discount_Percent")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<int?>("Reason_Id")
                        .HasColumnType("int");

                    b.Property<string>("ReturnId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<decimal>("Sub_Amount")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("Total_Discount")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("ReturnId");

                    b.ToTable("ReturnOrderDetails");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("Create_At")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<bool?>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.SellInvoice", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("OldInvoiceNo")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("OrderReturnId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("PrintDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNo");

                    b.HasIndex("OrderId");

                    b.ToTable("SellInvoices");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.SellInvoiceDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("ByUserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<int>("PosId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PrintDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("SellInvoiceDetails");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Source", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("Create_At")
                        .HasColumnType("datetime");

                    b.Property<string>("Desctiption")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<bool>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.SubCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("Company_Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("Create_At")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("Image")
                        .HasMaxLength(550)
                        .HasColumnType("varchar");

                    b.Property<bool?>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Main_Category_Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Main_Category_Id");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.SystemType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("Create_At")
                        .HasColumnType("datetime");

                    b.Property<bool?>("Is_Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("SystemTypes");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("Address")
                        .HasMaxLength(550)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Company_Id")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("Create_At")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<string>("Image")
                        .HasMaxLength(550)
                        .HasColumnType("varchar");

                    b.Property<bool?>("Is_Deleted")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasMaxLength(550)
                        .HasColumnType("nvarchar");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("User_Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Company_Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.UserLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoginAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LogoutAt")
                        .HasColumnType("datetime");

                    b.Property<int>("PosId")
                        .HasColumnType("int");

                    b.Property<string>("User_Id")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("User_Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("User_Id");

                    b.ToTable("UserLogs");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Category", b =>
                {
                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.Menu", "Menu")
                        .WithMany("Categories")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.ChangeShift", b =>
                {
                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.User", "User")
                        .WithMany("ChangShifts")
                        .HasForeignKey("Change_Shift_By")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.Company", "Company")
                        .WithMany("ChangShifts")
                        .HasForeignKey("Company_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.UserLog", "UserLog")
                        .WithMany("ChangShifts")
                        .HasForeignKey("UserLogId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");

                    b.Navigation("UserLog");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.ChangeShiftDetail", b =>
                {
                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.ChangeShift", "ChangShift")
                        .WithMany("ChangeShiftDetails")
                        .HasForeignKey("ChangeShift_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.PaymentMethod", "PaymentMethod")
                        .WithMany("ChangeShiftDetails")
                        .HasForeignKey("PaymentMethod_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChangShift");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Company", b =>
                {
                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.SystemType", "SystemType")
                        .WithMany("Companies")
                        .HasForeignKey("System_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SystemType");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Division", b =>
                {
                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.Company", "Company")
                        .WithMany("Divisions")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Menu", b =>
                {
                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.Division", "Division")
                        .WithMany("Menus")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Division");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Order", b =>
                {
                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("Reference_Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.ChangeShift", "ChangeShift")
                        .WithMany("Orders")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChangeShift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.OrderDetail", b =>
                {
                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("Order_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("Product_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.OrderPayment", b =>
                {
                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.CustomerType", "CustomerType")
                        .WithMany("OrderPayments")
                        .HasForeignKey("CustomerTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.Order", "Order")
                        .WithMany("OrderPayments")
                        .HasForeignKey("Order_Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.PaymentType", "PaymentType")
                        .WithMany("OrderPayments")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.User", "User")
                        .WithMany("OrderPayments")
                        .HasForeignKey("Reference")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.Source", "Source")
                        .WithMany("OrderPayments")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CustomerType");

                    b.Navigation("Order");

                    b.Navigation("PaymentType");

                    b.Navigation("Source");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Product", b =>
                {
                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("Category_Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("Company_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("Create_By")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("SubCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.ProductDiscount", b =>
                {
                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.DiscountType", "DiscountType")
                        .WithMany("ProductDiscounts")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.Product", "Product")
                        .WithMany("ProductDiscounts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DiscountType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.ReturnOrder", b =>
                {
                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.User", "User")
                        .WithMany("ReturnOrders")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.ReturnOrderDetail", b =>
                {
                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.ReturnOrder", "ReturnOrder")
                        .WithMany("Details")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ReturnOrder");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.SellInvoice", b =>
                {
                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.Order", "Order")
                        .WithMany("SellInvoices")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.SellInvoiceDetail", b =>
                {
                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.SellInvoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.SubCategory", b =>
                {
                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("Main_Category_Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.User", b =>
                {
                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("Company_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.UserLog", b =>
                {
                    b.HasOne("CashierPOS.WebApi.Models.EntityModel.User", "User")
                        .WithMany("UserLog")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.ChangeShift", b =>
                {
                    b.Navigation("ChangeShiftDetails");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Company", b =>
                {
                    b.Navigation("ChangShifts");

                    b.Navigation("Divisions");

                    b.Navigation("Products");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.CustomerType", b =>
                {
                    b.Navigation("OrderPayments");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.DiscountType", b =>
                {
                    b.Navigation("ProductDiscounts");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Division", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Menu", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("OrderPayments");

                    b.Navigation("SellInvoices");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.PaymentMethod", b =>
                {
                    b.Navigation("ChangeShiftDetails");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.PaymentType", b =>
                {
                    b.Navigation("OrderPayments");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Product", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("ProductDiscounts");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.ReturnOrder", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.SellInvoice", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.Source", b =>
                {
                    b.Navigation("OrderPayments");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.SubCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.SystemType", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.User", b =>
                {
                    b.Navigation("ChangShifts");

                    b.Navigation("OrderPayments");

                    b.Navigation("Orders");

                    b.Navigation("Products");

                    b.Navigation("ReturnOrders");

                    b.Navigation("UserLog");
                });

            modelBuilder.Entity("CashierPOS.WebApi.Models.EntityModel.UserLog", b =>
                {
                    b.Navigation("ChangShifts");
                });
#pragma warning restore 612, 618
        }
    }
}
